import XCTest

final class SkillRouterCompatibilityContractTests: XCTestCase {
    private var repoRoot: URL {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent() // PhoneClawCoreTests
            .deletingLastPathComponent() // Tests
            .deletingLastPathComponent() // Tests
            .deletingLastPathComponent() // repo root
    }

    private func source(_ relativePath: String) throws -> String {
        try String(contentsOf: repoRoot.appendingPathComponent(relativePath), encoding: .utf8)
    }

    private func fileExists(_ relativePath: String) -> Bool {
        FileManager.default.fileExists(atPath: repoRoot.appendingPathComponent(relativePath).path)
    }

    func testProductionSourcesDoNotImportIOS27OnlyFrameworksWithoutGuards() throws {
        let productionDirectories = ["Agent", "LLM", "Shared", "Skills", "Tools", "UI", "Live", "App"]
        let forbiddenImports = ["import FoundationModels", "import CoreAI"]
        let fileManager = FileManager.default

        for directory in productionDirectories {
            let root = repoRoot.appendingPathComponent(directory)
            guard let enumerator = fileManager.enumerator(
                at: root,
                includingPropertiesForKeys: nil,
                options: [.skipsHiddenFiles]
            ) else {
                continue
            }

            for case let fileURL as URL in enumerator where fileURL.pathExtension == "swift" {
                let content = try String(contentsOf: fileURL, encoding: .utf8)
                for forbiddenImport in forbiddenImports {
                    guard content.contains(forbiddenImport) else { continue }
                    XCTAssertTrue(
                        fileURL.lastPathComponent.hasPrefix("IOS27") && content.contains("#if canImport("),
                        "\(fileURL.path) must guard \(forbiddenImport) behind an iOS 27 compatibility boundary"
                    )
                }
            }
        }
    }

    func testGuardedDirectAnswerBlocksModelIntentFallback() throws {
        let processInput = try source("Agent/Engine/ProcessInput.swift")

        XCTAssertTrue(processInput.contains("guardedRouteBlocksModelIntent"))
        XCTAssertTrue(processInput.contains("!guardedRouteBlocksModelIntent"))
        XCTAssertTrue(processInput.contains("guardedRouteDecision?.action == .answerDirectly"))
    }

    func testIOS27FoundationRouterIsAutoEnabledAndFallbackOnly() throws {
        let flags = try source("Agent/HotfixFeatureFlags.swift")
        let processInput = try source("Agent/Engine/ProcessInput.swift")
        let router = try source("Agent/Engine/Router.swift")
        let ios27Router = try source("Agent/Engine/IOS27FoundationSkillRouter.swift")

        XCTAssertTrue(flags.contains("ENABLE_IOS27_FOUNDATION_ROUTER"))
        XCTAssertTrue(flags.contains("value(for: .enableIOS27FoundationRouter, defaultValue: true)"))
        XCTAssertTrue(processInput.contains("ios27FoundationSkillRouteDecision"))
        XCTAssertTrue(processInput.contains("!guardedRouteBlocksModelIntent"))
        XCTAssertTrue(processInput.contains("!ios27RouteBlocksModelIntent"))
        XCTAssertTrue(router.contains("shouldAttemptIOS27FoundationSkillRoute"))
        XCTAssertTrue(ios27Router.contains("#if canImport(FoundationModels)"))
        XCTAssertTrue(ios27Router.contains("if #available(iOS 27.0, macOS 27.0, *)"))
    }

    func testIOS27FoundationRouterUsesIOS27ModelAPIsWithDiagnostics() throws {
        let router = try source("Agent/Engine/Router.swift")
        let ios27Router = try source("Agent/Engine/IOS27FoundationSkillRouter.swift")

        XCTAssertTrue(ios27Router.contains("session.prewarm()"))
        XCTAssertTrue(ios27Router.contains("GenerationOptions("))
        XCTAssertTrue(ios27Router.contains("toolCallingMode: .disallowed"))
        XCTAssertTrue(ios27Router.contains("ContextOptions(includeSchemaInPrompt: true)"))
        XCTAssertTrue(ios27Router.contains("metadata: ["))
        XCTAssertTrue(ios27Router.contains("response.usage.input.totalTokenCount"))
        XCTAssertTrue(ios27Router.contains("response.usage.output.reasoningTokenCount"))
        XCTAssertTrue(router.contains("source=foundation_probe"))
        XCTAssertTrue(router.contains("prewarm_ms="))
        XCTAssertTrue(router.contains("route_ms="))
        XCTAssertTrue(router.contains("total_tokens="))
    }

    func testRouteSourceLogsAreStandardized() throws {
        let processInput = try source("Agent/Engine/ProcessInput.swift")
        let router = try source("Agent/Engine/Router.swift")

        XCTAssertTrue(processInput.contains("source=trigger"))
        XCTAssertTrue(router.contains("source=guarded"))
        XCTAssertTrue(router.contains("source=foundation"))
        XCTAssertTrue(router.contains("source=model"))
    }

    func testLiveSkillInfoDisplayDoesNotExposeRawToolJSON() throws {
        let liveOutputEvent = try source("Live/Turn/Types/LiveOutputEvent.swift")

        XCTAssertTrue(liveOutputEvent.contains("case skillInfo(LiveSkillInfoOutput)"))
        XCTAssertTrue(liveOutputEvent.contains("jsonPayload(from: detail)"))
        XCTAssertTrue(liveOutputEvent.contains("looksMachineReadable"))
        XCTAssertTrue(liveOutputEvent.contains("\"eventid\""))
        XCTAssertTrue(liveOutputEvent.contains("normalizedSummary + \"\\n\\n\" + appendableDetail"))
        XCTAssertFalse(liveOutputEvent.contains("userVisibleAnswer(from: normalizedSummary)"))
        XCTAssertFalse(liveOutputEvent.contains("isGroundedSourceTool(toolName)"))
        XCTAssertFalse(liveOutputEvent.contains("private static func isSourceMetadataLine(_ text: String) -> Bool"))
        XCTAssertFalse(liveOutputEvent.contains("normalizedSummary + \"\\n\\n\" + String(normalizedDetail.prefix"))
    }

    func testLiveBackgroundContinuationPreservesContinuedProcessingPath() throws {
        let continuation = try source("Live/Core/LiveBackgroundContinuation.swift")
        let infoPlist = try source("Info.plist")
        let entitlements = try source("PhoneClaw.entitlements")
        let app = try source("App/PhoneClawApp.swift")

        XCTAssertTrue(continuation.contains("static let taskIdentifier = \"com.kellyvv.phoneclaw.live-continuation\""))
        XCTAssertTrue(continuation.contains("registrationAccepted"))
        XCTAssertTrue(continuation.contains("submit skipped: no registered launch handler"))
        XCTAssertTrue(continuation.contains("BGContinuedProcessingTaskRequest("))
        XCTAssertTrue(continuation.contains("identifier: requestIdentifier"))
        XCTAssertTrue(continuation.contains("func begin(title: String = \"PhoneClaw LIVE\", subtitle: String = \"Listening\")"))
        XCTAssertTrue(continuation.contains("private var activeTitle = \"PhoneClaw LIVE\""))
        XCTAssertTrue(continuation.contains("title: title"))
        XCTAssertTrue(continuation.contains("cancel(taskRequestWithIdentifier: Self.taskIdentifier)"))
        XCTAssertTrue(infoPlist.contains("<string>audio</string>"))
        XCTAssertTrue(infoPlist.contains("BGTaskSchedulerPermittedIdentifiers"))
        XCTAssertTrue(infoPlist.contains("com.kellyvv.phoneclaw.live-continuation"))
        XCTAssertTrue(entitlements.contains("continued-processing"))
        XCTAssertTrue(app.contains("LiveBackgroundContinuation.shared.register()"))
        XCTAssertTrue(continuation.contains("BGTaskScheduler.supportedResources.contains(.gpu)"))
        XCTAssertTrue(continuation.contains("task.setTaskCompleted(success: success)"))
        XCTAssertTrue(continuation.contains("reason: \"expired_by_system\""))
        XCTAssertTrue(continuation.contains("case \"understanding\": return 55"))
        XCTAssertTrue(continuation.contains("case \"searching\", \"executing\": return 72"))
        XCTAssertTrue(continuation.contains("case \"summarizing\": return 84"))
        XCTAssertTrue(continuation.contains("case \"result\": return 95"))
    }

    func testLiveActivityDismissalStopsLiveSession() throws {
        let bridge = try source("Live/Activity/LiveActivityBridge.swift")
        let liveModeEngine = try source("Live/Core/LiveModeEngine.swift")
        let liveModeUI = try source("Live/UI/LiveModeUI.swift")

        XCTAssertTrue(bridge.contains("func waitForDismissal() async -> Bool"))
        XCTAssertTrue(bridge.contains("endExistingActivitiesBeforeRequest("))
        XCTAssertTrue(bridge.contains("entryPoint: entryPoint"))
        XCTAssertTrue(bridge.contains("Activity<PhoneClawLiveActivityAttributes>.activities"))
        XCTAssertTrue(bridge.contains("ended stale activity before request"))
        XCTAssertTrue(bridge.contains("activity.activityStateUpdates"))
        XCTAssertTrue(bridge.contains("case .dismissed:"))
        XCTAssertTrue(bridge.contains("dismissed by user"))

        XCTAssertTrue(liveModeEngine.contains("endedByLiveActivityDismissal"))
        XCTAssertTrue(liveModeEngine.contains("liveActivityDismissalTask"))
        XCTAssertTrue(liveModeEngine.contains("observeLiveActivityDismissal()"))
        XCTAssertTrue(liveModeEngine.contains("await self.liveActivity.waitForDismissal()"))
        XCTAssertTrue(liveModeEngine.contains("stopFromLiveActivityDismissal()"))
        XCTAssertTrue(liveModeEngine.contains("await stopLegacy()"))
        XCTAssertTrue(liveModeEngine.contains("cancelLiveActivityDismissalObservation()"))

        XCTAssertTrue(liveModeUI.contains(".onChange(of: liveEngine.endedByLiveActivityDismissal)"))
        XCTAssertTrue(liveModeUI.contains("isPresented = false"))
    }

    func testLiveLandEntryStartsDedicatedMicrophoneSession() throws {
        let shortcuts = try source("App/LiveLandShortcuts.swift")
        let agentEngine = try source("Agent/AgentEngine.swift")
        let toolChain = try source("Agent/Engine/ToolChain.swift")
        let planner = try source("Agent/Engine/Planner.swift")
        let contentView = try source("UI/ContentView.swift")
        let liveModeUI = try source("Live/UI/LiveModeUI.swift")
        let liveModeEngine = try source("Live/Core/LiveModeEngine.swift")
        let attributes = try source("Live/Activity/PhoneClawLiveActivityAttributes.swift")
        let bridge = try source("Live/Activity/LiveActivityBridge.swift")
        let audioIO = try source("Live/Audio/LiveAudioIO.swift")
        let asrService = try source("Shared/Audio/ASRService.swift")
        let appShortcuts = shortcuts.components(separatedBy: "static var appShortcuts").last ?? shortcuts

        XCTAssertTrue(shortcuts.contains("struct OpenLiveLandIntent: AppIntent"))
        XCTAssertTrue(shortcuts.contains("import CoreHaptics"))
        XCTAssertTrue(shortcuts.contains("import UIKit"))
        XCTAssertTrue(shortcuts.contains("Open PhoneClaw and start LiveLand microphone listening in Dynamic Island."))
        XCTAssertTrue(shortcuts.contains("static var openAppWhenRun: Bool = true"))
        XCTAssertTrue(shortcuts.contains("LiveLaunchRequestStore.requestLiveLandLaunch()"))
        XCTAssertTrue(shortcuts.contains("final class LiveLandVoiceRuntime"))
        XCTAssertTrue(shortcuts.contains("private final class LiveLandSkillPromptHaptics"))
        XCTAssertTrue(shortcuts.contains("UIImpactFeedbackGenerator(style: .rigid)"))
        XCTAssertFalse(shortcuts.contains("UINotificationFeedbackGenerator()"))
        XCTAssertTrue(shortcuts.contains("CHHapticEngine.capabilitiesForHardware().supportsHaptics"))
        XCTAssertTrue(shortcuts.contains("private func playUnlockClickPattern() -> Bool"))
        XCTAssertTrue(shortcuts.contains("eventType: .hapticTransient"))
        XCTAssertTrue(shortcuts.contains("parameterID: .hapticIntensity, value: 1.0"))
        XCTAssertTrue(shortcuts.contains("parameterID: .hapticSharpness, value: 1.0"))
        XCTAssertTrue(shortcuts.contains("relativeTime: 0.045"))
        XCTAssertTrue(shortcuts.contains("impactFallback.impactOccurred(intensity: 1.0)"))
        XCTAssertTrue(shortcuts.contains("private let skillPromptHaptics = LiveLandSkillPromptHaptics()"))
        XCTAssertTrue(shortcuts.contains("skillPromptHaptics.prepare()"))
        XCTAssertTrue(shortcuts.contains("playSkillPromptHaptic(for: promptToPublish.detail)"))
        XCTAssertTrue(audioIO.contains("setAllowHapticsAndSystemSoundsDuringRecording(true)"))
        XCTAssertFalse(shortcuts.contains("struct LiveLandSessionView: View"))
        XCTAssertTrue(shortcuts.contains("let io = LiveAudioIO()"))
        XCTAssertTrue(shortcuts.contains("try await io.startForLiveLand()"))
        XCTAssertTrue(shortcuts.contains("try await io.startForLiveLand()\n            skillPromptHaptics.prepare()"))
        XCTAssertTrue(shortcuts.contains("await vad.startListening(audioIO: io)"))
        XCTAssertTrue(shortcuts.contains("vad.onSpeechChunk = { [weak self] chunk in"))
        XCTAssertTrue(shortcuts.contains("beginStreamingASRTurn()"))
        XCTAssertTrue(shortcuts.contains("asr.beginStreaming()"))
        XCTAssertTrue(shortcuts.contains("asr.appendStreaming(samples: chunk)"))
        XCTAssertTrue(shortcuts.contains("asr.endStreaming()"))
        XCTAssertTrue(shortcuts.contains("asr.cancelStreaming()"))
        XCTAssertTrue(shortcuts.contains("setTranscript(text)"))
        XCTAssertTrue(shortcuts.contains("print(\"[LiveLand] ASR streaming start\")"))
        XCTAssertTrue(shortcuts.contains("print(\"[LiveLand] ASR partial:"))
        XCTAssertTrue(shortcuts.contains("print(\"[LiveLand] ASR partial correction:"))
        XCTAssertTrue(shortcuts.contains("print(\"[LiveLand] ASR full-turn correction:"))
        XCTAssertTrue(shortcuts.contains("print(\"[LiveLand] ASR full-turn start:"))
        XCTAssertTrue(shortcuts.contains("print(\"[LiveLand] ASR full-turn done:"))
        XCTAssertTrue(shortcuts.contains("await asr.transcribe(samples: samples)"))
        XCTAssertTrue(shortcuts.contains("let liveLandMessages = await agentEngine.processLiveLandCommand(transcript)"))
        XCTAssertFalse(shortcuts.contains("await agentEngine.processInput(transcript)"))
        XCTAssertTrue(shortcuts.contains("private let backgroundContinuation = LiveBackgroundContinuation.shared"))
        XCTAssertFalse(shortcuts.contains("backgroundContinuation.begin(title: \"LiveLand\""))
        XCTAssertFalse(shortcuts.contains("backgroundContinuation.update(phase: \"listening\""))
        XCTAssertFalse(shortcuts.contains("正在监听"))
        XCTAssertTrue(shortcuts.contains("backgroundContinuation.end(success: true)\n        await liveActivity.startSession(headline: \"LiveLand\", entryPoint: \"liveLand\")"))
        XCTAssertTrue(shortcuts.contains("detail: \"\""))
        XCTAssertTrue(shortcuts.contains("private static let startupConfirmationDwell: Duration = .milliseconds(900)"))
        XCTAssertTrue(shortcuts.contains("LiveLand 已启动"))
        XCTAssertTrue(shortcuts.contains("prepareRuntimeForBackgroundLiveLand(agentEngine: agentEngine)"))
        XCTAssertTrue(shortcuts.contains("startBackgroundRuntimePreparation(agentEngine: agentEngine)"))
        XCTAssertTrue(shortcuts.contains("ensureRuntimeReadyForLiveLandAgent(agentEngine: agentEngine)"))
        XCTAssertTrue(shortcuts.contains("backgroundContinuation.supportsBackgroundGPU"))
        XCTAssertTrue(shortcuts.contains("switchBackend(to: \"cpu\")"))
        XCTAssertTrue(shortcuts.contains("restoreRuntimeAfterLiveLand(agentEngine: engine)"))
        XCTAssertTrue(shortcuts.contains("cancelActiveAgentWork(agentEngine: engine)"))
        XCTAssertTrue(shortcuts.contains("await liveActivity.startSession(headline: \"LiveLand\", entryPoint: \"liveLand\")"))
        XCTAssertTrue(shortcuts.contains("await liveActivity.endSession(headline: \"LiveLand\", entryPoint: \"liveLand\")"))
        XCTAssertTrue(shortcuts.contains("let previousActivityEventSink = agentEngine.activityEventSink"))
        XCTAssertTrue(shortcuts.contains("agentEngine.activityEventSink = { [weak self] event in"))
        XCTAssertTrue(shortcuts.contains("await self?.scheduleSkillPrompt(for: event, generation: generation)"))
        XCTAssertTrue(shortcuts.contains("headline: \"LiveLand\""))
        XCTAssertTrue(shortcuts.contains("agentEngine.activityEventSink = previousActivityEventSink"))
        XCTAssertFalse(shortcuts.contains("private static let skillPromptDelay"))
        XCTAssertTrue(shortcuts.contains("private static let skillPromptMinimumDwellSeconds: TimeInterval = 0.8"))
        XCTAssertTrue(shortcuts.contains("private var liveActivitySkillSignalSeen = false"))
        XCTAssertTrue(shortcuts.contains("private var hasVisibleSkillPresentation = false"))
        XCTAssertTrue(shortcuts.contains("private var pendingSkillPrompt: SkillPrompt?"))
        XCTAssertTrue(shortcuts.contains("private var skillPromptTask: Task<Void, Never>?"))
        XCTAssertTrue(shortcuts.contains("private var visibleSkillPromptStartedAt: Date?"))
        XCTAssertTrue(shortcuts.contains("private func scheduleSkillPrompt(for event: AgentActivityEvent, generation: UInt64) async"))
        XCTAssertTrue(shortcuts.contains("await liveActivity.update(\n            phase: prompt.phase"))
        XCTAssertFalse(shortcuts.contains("try? await Task.sleep(for: Self.skillPromptDelay)"))
        XCTAssertTrue(shortcuts.contains("private func waitForVisibleSkillPromptMinimumDwell(generation: UInt64) async -> Bool"))
        XCTAssertTrue(shortcuts.contains("Self.skillPromptMinimumDwellSeconds"))
        XCTAssertTrue(shortcuts.contains("liveActivitySkillSignalSeen = true"))
        XCTAssertTrue(shortcuts.contains("self.hasVisibleSkillPresentation = true"))
        XCTAssertTrue(shortcuts.contains("visibleSkillPromptStartedAt = Date()"))
        XCTAssertTrue(shortcuts.contains("private enum IslandStatus: String, Sendable"))
        XCTAssertTrue(shortcuts.contains("case querying = \"正在查询\""))
        XCTAssertTrue(shortcuts.contains("case executing = \"正在执行\""))
        XCTAssertTrue(shortcuts.contains("case processing = \"正在处理\""))
        XCTAssertTrue(shortcuts.contains("case summarizing = \"正在整理\""))
        XCTAssertTrue(shortcuts.contains("case result = \"结果展示\""))
        XCTAssertTrue(shortcuts.contains("case .querying:\n                return \"searching\""))
        XCTAssertTrue(shortcuts.contains("case .executing, .processing:\n                return \"executing\""))
        XCTAssertTrue(shortcuts.contains("case .summarizing:\n                return \"summarizing\""))
        XCTAssertTrue(shortcuts.contains("case .result:\n                return \"result\""))
        XCTAssertTrue(shortcuts.contains("private func islandStatus(for event: AgentActivityEvent) -> IslandStatus"))
        XCTAssertTrue(shortcuts.contains("case .processing:\n            return .processing"))
        XCTAssertTrue(shortcuts.contains("case .executing:\n            return .executing"))
        XCTAssertFalse(shortcuts.contains("private func isQuerySkillKey"))
        XCTAssertFalse(shortcuts.contains("private func isActionSkillKey"))
        XCTAssertTrue(shortcuts.contains("private func showFinalResult("))
        XCTAssertTrue(shortcuts.contains("await showFinalResult(message, success: false, status: message)"))
        XCTAssertTrue(shortcuts.contains("_ = await liveActivity.presentTransientResult("))
        XCTAssertTrue(shortcuts.contains("entryPoint: \"liveLand\""))
        XCTAssertTrue(shortcuts.contains("allowTransientRequest: true"))
        XCTAssertFalse(shortcuts.contains("allowTransientRequest: !isAppInBackground"))
        XCTAssertTrue(shortcuts.contains("await liveActivity.startSession(headline: \"LiveLand\", detail: \"\", entryPoint: \"liveLand\")"))
        XCTAssertTrue(shortcuts.contains("playSkillPromptHaptic(for: IslandStatus.result.rawValue)"))
        XCTAssertTrue(shortcuts.contains("private func islandResultDialog(for result: LiveLandAgentResult) -> String"))
        XCTAssertTrue(shortcuts.contains("return \"未完成\\n\\(dialog)\""))
        XCTAssertTrue(bridge.contains("phase: \"result\""))
        XCTAssertTrue(bridge.contains("allowTransientRequest: Bool = true"))
        XCTAssertFalse(bridge.contains("publishStandardResultFallback"))
        XCTAssertFalse(bridge.contains("standard result publish"))
        XCTAssertFalse(bridge.contains("transient result skipped: target not foreground"))
        XCTAssertTrue(bridge.contains("publishExpandedResultAlert(content: content)"))
        XCTAssertTrue(bridge.contains("private func publishExpandedResultAlert("))
        XCTAssertTrue(bridge.contains("result expanded alert update id="))
        XCTAssertTrue(bridge.contains("transient result blocked by caller"))
        XCTAssertTrue(bridge.contains("alertConfiguration: alertConfiguration"))
        XCTAssertFalse(bridge.contains("endStandardActivitiesBeforeTransientResult(content: content)"))
        XCTAssertFalse(shortcuts.contains("alertTitle: result.success ? nil : \"LiveLand\""))
        XCTAssertFalse(shortcuts.contains("alertBody: result.success ? nil : clipped(resultDialog, limit: 86)"))
        XCTAssertTrue(shortcuts.contains("if hasVisibleSkillPresentation"))
        XCTAssertFalse(shortcuts.contains("let shouldShowSkillResult = liveActivitySkillSignalSeen"))
        XCTAssertFalse(shortcuts.contains("guard shouldShowSkillResult else"))
        XCTAssertTrue(shortcuts.contains("let result = summarize(messages: liveLandMessages)\n        cancelPendingSkillPrompt()"))
        XCTAssertFalse(shortcuts.contains("private func hasSkillActivityResult(in messages: [ChatMessage], result: LiveLandAgentResult) -> Bool"))
        XCTAssertFalse(shortcuts.contains("phase: \"recording\""))
        XCTAssertFalse(shortcuts.contains("phase: \"understanding\""))
        XCTAssertFalse(shortcuts.contains("phase: \"processing\""))
        XCTAssertTrue(shortcuts.contains("phase: \"listening\""))
        XCTAssertTrue(shortcuts.contains("phase: \"result\""))
        XCTAssertTrue(shortcuts.contains("success: false"))
        XCTAssertTrue(shortcuts.contains("dialog: dialog"))
        XCTAssertTrue(shortcuts.contains("private static let shortPromptDwell: Duration = .milliseconds(2500)"))
        XCTAssertTrue(shortcuts.contains("private static let resultDwell: Duration = .seconds(12)"))
        XCTAssertTrue(shortcuts.contains("delay: Duration? = nil"))
        XCTAssertTrue(shortcuts.contains("let refreshDelay = delay ?? Self.shortPromptDwell"))
        XCTAssertTrue(shortcuts.contains("try? await Task.sleep(for: refreshDelay)"))
        XCTAssertTrue(shortcuts.contains("scheduleListeningRefresh(after: generation, delay: Self.resultDwell)"))
        XCTAssertTrue(shortcuts.contains("$0.skillName == nil"))
        XCTAssertTrue(shortcuts.contains("AppShortcut("))
        XCTAssertTrue(shortcuts.contains("OpenLiveLandIntent()"))
        XCTAssertTrue(shortcuts.contains("shortTitle: \"LiveLand\""))
        XCTAssertTrue(shortcuts.contains("\"Open \\(.applicationName) LiveLand\""))
        XCTAssertTrue(shortcuts.contains("\"Launch \\(.applicationName) LiveLand\""))
        XCTAssertTrue(shortcuts.contains("\"打开 \\(.applicationName) LiveLand\""))
        XCTAssertTrue(shortcuts.contains("StartPhoneClawLiveModeIntent()"))
        XCTAssertTrue(shortcuts.contains("shortTitle: \"LIVE Mode\""))
        XCTAssertFalse(shortcuts.contains("systemImageName: \"sparkles\""))
        XCTAssertFalse(appShortcuts.contains("AskLiveLandIntent()"))
        XCTAssertFalse(shortcuts.contains("struct AskLiveLandIntent"))
        XCTAssertFalse(shortcuts.contains("final class LiveLandAgentRuntime"))
        XCTAssertFalse(shortcuts.contains("LiveLandAgentRuntime.shared.run"))
        XCTAssertFalse(shortcuts.contains("\\(\\.$request)"))

        XCTAssertTrue(agentEngine.contains("@ObservationIgnored private var isSessionPersistenceEnabled = true"))
        XCTAssertTrue(agentEngine.contains("@ObservationIgnored var isLiveLandTurnActive = false"))
        XCTAssertTrue(agentEngine.contains("struct AgentActivityEvent"))
        XCTAssertTrue(agentEngine.contains("@ObservationIgnored var activityEventSink"))
        XCTAssertTrue(agentEngine.contains("func processLiveLandCommand(_ text: String) async -> [ChatMessage]"))
        XCTAssertTrue(agentEngine.contains("return liveLandSystemMessages(\"LiveLand 正在处理上一条指令，请稍后再试。\")"))
        XCTAssertTrue(agentEngine.contains("private func ensureLiveLandModelReady() async -> String?"))
        XCTAssertTrue(agentEngine.contains("请先在设置里下载模型，LiveLand 需要模型才能调用技能。"))
        XCTAssertTrue(agentEngine.contains("try await coordinator.load("))
        XCTAssertTrue(agentEngine.contains("let savedMessages = messages"))
        XCTAssertTrue(agentEngine.contains("await processInput(text)"))
        XCTAssertTrue(agentEngine.contains("await waitForLiveLandCommandCompletion()"))
        XCTAssertTrue(agentEngine.contains("guard isProcessing || isModelGenerating || inference.isGenerating else"))
        XCTAssertTrue(agentEngine.contains("cancelActiveGeneration()"))
        XCTAssertTrue(agentEngine.contains("isLiveLandTurnActive = true"))
        XCTAssertTrue(agentEngine.contains("isLiveLandTurnActive = false"))
        XCTAssertTrue(agentEngine.contains("messages = []"))
        XCTAssertTrue(agentEngine.contains("messages = savedMessages"))
        XCTAssertTrue(agentEngine.contains("func publishSkillActivityEvent"))
        XCTAssertTrue(agentEngine.contains("case processing"))
        XCTAssertTrue(agentEngine.contains("case summarizing"))
        XCTAssertTrue(agentEngine.contains("phase: AgentActivityEvent.Phase"))
        XCTAssertFalse(agentEngine.contains("phase: AgentActivityEvent.Phase? = nil"))
        XCTAssertFalse(agentEngine.contains("let resolvedPhase = phase ??"))
        XCTAssertFalse(agentEngine.contains("let isSearch ="))
        XCTAssertFalse(agentEngine.contains("toolKey.contains"))
        XCTAssertTrue(agentEngine.contains("case .processing:\n                return \"正在处理\""))
        XCTAssertTrue(agentEngine.contains("case .summarizing:\n                return \"正在整理\""))
        XCTAssertTrue(agentEngine.contains("func setSessionPersistenceEnabled(_ enabled: Bool)"))
        XCTAssertTrue(agentEngine.contains("if isSessionPersistenceEnabled"))
        XCTAssertTrue(agentEngine.contains("sessionStore.cancelPendingSave()"))
        XCTAssertTrue(toolChain.contains("toolName: call.name,\n            phase: .executing"))
        XCTAssertTrue(toolChain.contains("phase: .summarizing"))
        XCTAssertTrue(planner.contains("toolName: nil,\n                        phase: .executing"))
        XCTAssertTrue(planner.contains("toolName: step.tool,\n                    phase: .executing"))
        XCTAssertTrue(planner.contains("phase: .summarizing"))

        XCTAssertTrue(contentView.contains("@State private var showLiveLand = false"))
        XCTAssertTrue(contentView.contains("@State private var liveLandRuntime = LiveLandVoiceRuntime()"))
        XCTAssertTrue(contentView.contains("private var visibleConversationIsEmpty: Bool"))
        XCTAssertTrue(contentView.contains("engine.isLiveLandTurnActive ? cachedDisplayItems.isEmpty : engine.messages.isEmpty"))
        XCTAssertTrue(contentView.contains("if engine.isLiveLandTurnActive"))
        XCTAssertTrue(contentView.contains("guard !engine.isLiveLandTurnActive else { return }"))
        XCTAssertFalse(contentView.contains(".fullScreenCover(isPresented: $showLiveLand)"))
        XCTAssertFalse(contentView.contains("LiveLandSessionView("))
        XCTAssertTrue(contentView.contains("private func enterLiveLand()"))
        XCTAssertTrue(contentView.contains("showLiveLand = true"))
        XCTAssertTrue(contentView.contains("LiveWarmPool.shared.cancelPrewarm()"))
        XCTAssertTrue(contentView.contains("await liveLandRuntime.start(agentEngine: engine)"))
        XCTAssertTrue(contentView.contains("private func stopLiveLand(endLiveActivity: Bool = true)"))
        XCTAssertTrue(contentView.contains("enterLiveLand()"))
        XCTAssertTrue(contentView.contains("case .liveLand:"))
        XCTAssertFalse(contentView.contains("enterLiveMode(activityHeadline: \"LiveLand\")"))
        XCTAssertFalse(contentView.contains("liveModeActivityHeadline"))
        XCTAssertFalse(liveModeUI.contains("liveActivityHeadline"))
        XCTAssertFalse(liveModeEngine.contains("var liveActivityHeadline"))
        XCTAssertTrue(liveModeEngine.contains("let io = LiveAudioIO()"))
        XCTAssertTrue(liveModeEngine.contains("try io.start()"))
        XCTAssertTrue(liveModeEngine.contains("await vad.startListening(audioIO: io)"))
        XCTAssertTrue(liveModeEngine.contains("await liveActivity.startSession()"))
        XCTAssertTrue(liveModeEngine.contains("headline: \"PhoneClaw LIVE\""))
        XCTAssertTrue(liveModeEngine.contains("headline: \"正在理解\""))
        XCTAssertTrue(liveModeEngine.contains("headline: \"正在执行\""))
        XCTAssertTrue(liveModeEngine.contains("headline: output.displayName"))
        XCTAssertTrue(liveModeEngine.contains("phase: \"result\",\n            headline: output.displayName"))
        XCTAssertTrue(liveModeEngine.contains("backgroundContinuation.update(phase: \"result\", detail: displayText)"))
        XCTAssertFalse(liveModeEngine.contains("phase: \"skill\",\n            headline: output.displayName"))
        XCTAssertTrue(attributes.contains("var entryPoint: String?"))
        XCTAssertTrue(bridge.contains("entryPoint: String = \"liveMode\""))
        XCTAssertTrue(bridge.contains("entryPoint: entryPoint ?? self.entryPoint"))
        XCTAssertTrue(bridge.contains("func presentTransientResult("))
        XCTAssertTrue(bridge.contains(") async -> Bool"))
        XCTAssertTrue(bridge.contains("style: .transient"))
        XCTAssertTrue(bridge.contains("publishExpandedResultAlert(content: content)"))
        XCTAssertFalse(bridge.contains("standard result publish"))
        XCTAssertFalse(bridge.contains("ended standard activity before transient result"))
        XCTAssertTrue(asrService.contains("print(\"[ASR] Sherpa transcribe start:"))
        XCTAssertTrue(asrService.contains("print(\"[ASR] Sherpa transcribe done:"))
    }

    func testLiveLandLaunchRoutingSeparatesLiveLandFromLiveMode() throws {
        let route = try source("App/LiveLaunchRouting.swift")
        let contentView = try source("UI/ContentView.swift")

        XCTAssertTrue(route.contains("case liveLand"))
        XCTAssertTrue(route.contains("static var liveLandURL: URL"))
        XCTAssertTrue(route.contains("URL(string: \"\\(scheme)://liveland\")!"))
        XCTAssertTrue(route.contains("if host == \"liveland\" || path == \"liveland\""))
        XCTAssertTrue(route.contains("private static let pendingLiveLandLaunchKey = \"phoneclaw.pendingLiveLandLaunch\""))
        XCTAssertTrue(route.contains("requestLiveLandLaunch()"))
        XCTAssertTrue(route.contains("consumeLiveLandLaunchRequest()"))
        XCTAssertTrue(route.contains("requestVoiceLaunch()"))
        XCTAssertTrue(contentView.contains("case .liveLand:"))
        XCTAssertTrue(contentView.contains("LiveLaunchRequestStore.requestLiveLandLaunch()"))
        XCTAssertTrue(contentView.contains("consumePendingLiveLandLaunchIfNeeded()"))
        XCTAssertTrue(contentView.contains("enterLiveLand()"))
        XCTAssertTrue(contentView.contains("showLiveLand = true"))
        XCTAssertFalse(contentView.contains("LiveLandAgentRuntime.shared.openIsland()"))
        XCTAssertTrue(contentView.contains("case .voice:"))
        XCTAssertTrue(contentView.contains("consumePendingLiveLaunchIfNeeded()"))
    }

    func testLiveLandLauncherWidgetSupportsLockScreenAndHomeScreenEntryPoints() throws {
        let widget = try source("PhoneClawLiveActivityWidget/PhoneClawLiveActivityWidget.swift")
        let infoPlist = try source("PhoneClawLiveActivityWidget/Info.plist")

        XCTAssertTrue(widget.contains("private let phoneClawLiveModeLaunchURL = URL(string: \"phoneclaw://live?mode=voice\")!"))
        XCTAssertTrue(widget.contains("private let phoneClawLiveLandLaunchURL = URL(string: \"phoneclaw://liveland\")!"))
        XCTAssertTrue(widget.contains("PhoneClawLiveLandLauncherWidget()"))
        XCTAssertTrue(widget.contains("kind: \"PhoneClawLiveLandLauncherWidget\""))
        XCTAssertTrue(widget.contains(".widgetURL(phoneClawLiveLandLaunchURL)"))
        XCTAssertTrue(widget.contains(".configurationDisplayName(\"LiveLand\")"))
        XCTAssertTrue(widget.contains(".description(\"Open PhoneClaw and start LiveLand microphone listening.\")"))
        XCTAssertTrue(widget.contains(".supportedFamilies(["))
        XCTAssertTrue(widget.contains(".systemSmall"))
        XCTAssertTrue(widget.contains(".accessoryCircular"))
        XCTAssertTrue(widget.contains(".accessoryRectangular"))
        XCTAssertTrue(widget.contains(".accessoryInline"))
        XCTAssertTrue(widget.contains("@Environment(\\.widgetFamily)"))
        XCTAssertTrue(widget.contains("case .accessoryCircular"))
        XCTAssertTrue(widget.contains("case .accessoryRectangular"))
        XCTAssertTrue(widget.contains("case .accessoryInline"))
        XCTAssertTrue(widget.contains("AccessoryWidgetBackground()"))
        XCTAssertTrue(widget.contains("import UIKit"))
        XCTAssertTrue(widget.contains("UIImage(named: \"liveland_launcher\", in: .main, compatibleWith: nil)"))
        XCTAssertTrue(widget.contains("LiveLandLauncherMark(size: 76, style: .badge)"))
        XCTAssertTrue(widget.contains("Image(uiImage: image)"))
        XCTAssertTrue(widget.contains("private var liveLandLauncherImage: some View"))
        XCTAssertTrue(widget.contains(".frame(width: 76, height: 76)"))
        XCTAssertTrue(widget.contains(".renderingMode(.original)"))
        XCTAssertTrue(widget.contains("private struct LiveLandLauncherMark: View"))
        XCTAssertTrue(widget.contains("private struct LiveLandListeningBars: View"))
        XCTAssertTrue(widget.contains("LiveLandLauncherMark(size: 26, style: .pill)"))
        XCTAssertTrue(widget.contains("LiveLandLauncherMark(size: 20, style: .barsOnly)"))
        XCTAssertTrue(widget.contains("Text(\"LiveLand\")"))
        XCTAssertTrue(widget.contains("Text(\"PhoneClaw LiveLand\")"))
        XCTAssertTrue(widget.contains("Label(\"LiveLand\", systemImage: \"waveform\")"))
        XCTAssertFalse(widget.contains("systemImage: \"sparkles\""))
        XCTAssertFalse(widget.contains("Text(\"LIVE\")"))
        XCTAssertFalse(widget.contains("Label(\"PhoneClaw LIVE\", systemImage: \"waveform\")"))
        XCTAssertTrue(infoPlist.contains("<string>LiveLand</string>"))
    }

    func testLiveLandLauncherAndAppIconAssetsArePackagedForSystemSurfaces() throws {
        let widgetAsset = try source("PhoneClawLiveActivityWidget/Assets.xcassets/liveland_launcher.imageset/Contents.json")
        let appIcon = try source("Assets.xcassets/AppIcon.appiconset/Contents.json")
        let iconComposer = try source("AppIcon.icon/icon.json")
        let project = try source("PhoneClaw.xcodeproj/project.pbxproj")

        XCTAssertTrue(widgetAsset.contains("\"filename\" : \"liveland_launcher.png\""))
        XCTAssertTrue(widgetAsset.contains("\"filename\" : \"liveland_launcher@2x.png\""))
        XCTAssertTrue(widgetAsset.contains("\"filename\" : \"liveland_launcher@3x.png\""))

        XCTAssertTrue(fileExists("PhoneClawLiveActivityWidget/Assets.xcassets/liveland_launcher.imageset/liveland_launcher.png"))
        XCTAssertTrue(fileExists("PhoneClawLiveActivityWidget/Assets.xcassets/liveland_launcher.imageset/liveland_launcher@2x.png"))
        XCTAssertTrue(fileExists("PhoneClawLiveActivityWidget/Assets.xcassets/liveland_launcher.imageset/liveland_launcher@3x.png"))

        XCTAssertTrue(appIcon.contains("\"idiom\": \"iphone\""))
        XCTAssertTrue(appIcon.contains("\"idiom\": \"ipad\""))
        XCTAssertTrue(appIcon.contains("\"idiom\": \"ios-marketing\""))
        XCTAssertTrue(appIcon.contains("\"filename\": \"AppIcon-60@2x.png\""))
        XCTAssertTrue(appIcon.contains("\"filename\": \"AppIcon-60@3x.png\""))
        XCTAssertTrue(appIcon.contains("\"filename\": \"AppIcon-76@2x.png\""))
        XCTAssertTrue(appIcon.contains("\"filename\": \"AppIcon-1024.png\""))

        XCTAssertTrue(fileExists("Assets.xcassets/AppIcon.appiconset/AppIcon-60@2x.png"))
        XCTAssertTrue(fileExists("Assets.xcassets/AppIcon.appiconset/AppIcon-60@3x.png"))
        XCTAssertTrue(fileExists("Assets.xcassets/AppIcon.appiconset/AppIcon-76@2x.png"))
        XCTAssertTrue(fileExists("Assets.xcassets/AppIcon.appiconset/AppIcon-1024.png"))

        XCTAssertTrue(iconComposer.contains("\"supported-platforms\""))
        XCTAssertTrue(iconComposer.contains("\"squares\""))
        XCTAssertTrue(iconComposer.contains("\"iOS\""))
        XCTAssertTrue(iconComposer.contains("\"image-name\" : \"phoneclaw-icon.png\""))
        XCTAssertTrue(fileExists("AppIcon.icon/Assets/phoneclaw-icon.png"))

        XCTAssertTrue(project.contains("folder.iconcomposer.icon"))
        XCTAssertTrue(project.contains("AppIcon.icon in Resources"))
    }

    func testLiveLandControlWidgetSupportsControlCenterEntryPoint() throws {
        let widget = try source("PhoneClawLiveActivityWidget/PhoneClawLiveActivityWidget.swift")

        XCTAssertTrue(widget.contains("import AppIntents"))
        XCTAssertTrue(widget.contains("if #available(iOS 18.0, *)"))
        XCTAssertTrue(widget.contains("PhoneClawLiveLandControlWidget()"))
        XCTAssertTrue(widget.contains("struct PhoneClawLiveLandControlWidget: ControlWidget"))
        XCTAssertTrue(widget.contains("StaticControlConfiguration(kind: \"PhoneClawLiveLandControlWidget\")"))
        XCTAssertTrue(widget.contains("ControlWidgetButton(action: OpenURLIntent(phoneClawLiveLandLaunchURL))"))
        XCTAssertTrue(widget.contains("Label(\"LiveLand\", systemImage: \"waveform\")"))
        XCTAssertFalse(widget.contains("systemImage: \"sparkles\""))
        XCTAssertTrue(widget.contains(".displayName(\"LiveLand\")"))
        XCTAssertTrue(widget.contains(".description(\"Open PhoneClaw and start LiveLand microphone listening.\")"))
    }

    func testLiveDynamicIslandSeparatesVoiceAndThinkingGlyphs() throws {
        let widget = try source("PhoneClawLiveActivityWidget/PhoneClawLiveActivityWidget.swift")
        let attributes = try source("Live/Activity/PhoneClawLiveActivityAttributes.swift")
        let bridge = try source("Live/Activity/LiveActivityBridge.swift")

        XCTAssertTrue(widget.contains("private enum LiveIslandStage"))
        XCTAssertTrue(widget.contains("private enum LiveIslandVisualPhase"))
        XCTAssertTrue(widget.contains("private struct LiveIslandPresentation"))
        XCTAssertTrue(widget.contains("diameter: presentation.expandedGlyphDiameter"))
        XCTAssertTrue(widget.contains("var expandedGlyphDiameter: CGFloat"))
        XCTAssertTrue(widget.contains("diameter: presentation.visualPhase == .voice ? 22 : 24"))
        XCTAssertTrue(widget.contains("LiveIslandCoreVisual(presentation: presentation, diameter: 18)"))
        XCTAssertTrue(widget.contains("private enum LiveTheme"))
        XCTAssertTrue(widget.contains("static let signal = Color"))
        XCTAssertTrue(widget.contains("private struct LiveIslandCoreVisual: View"))
        XCTAssertTrue(widget.contains("private struct LiveListeningBarsGlyph: View"))
        XCTAssertTrue(widget.contains("private struct LiveSkillOrbitGlyph: View"))
        XCTAssertTrue(widget.contains("private struct LiveResultGlyph: View"))
        XCTAssertTrue(widget.contains("private struct LiveIslandSkillStatusLabel: View"))
        XCTAssertTrue(widget.contains("private struct LiveIslandCompactTrailing: View"))
        XCTAssertFalse(widget.contains("private struct LiveIslandResultCompactPreview: View"))
        XCTAssertTrue(widget.contains("private struct LiveResultExpandedText: View"))
        XCTAssertFalse(widget.contains("private struct LiveResultFooter: View"))
        XCTAssertTrue(widget.contains("private struct LiveIdleMark: View"))
        XCTAssertFalse(attributes.contains("motionTick"))
        XCTAssertTrue(attributes.contains("var entryPoint: String?"))
        XCTAssertTrue(widget.contains("state.entryPoint == \"liveLand\""))
        XCTAssertTrue(bridge.contains("entryPoint: String = \"liveMode\""))
        XCTAssertFalse(bridge.contains("motionInterval"))
        XCTAssertFalse(bridge.contains("motionPhases"))
        XCTAssertFalse(bridge.contains("motionTask"))
        XCTAssertFalse(bridge.contains("publishMotionTick"))
        XCTAssertFalse(bridge.contains("try? await Task.sleep(for: .milliseconds(160))"))
        XCTAssertTrue(widget.contains("var primaryLine: String"))
        XCTAssertTrue(widget.contains("var hasStartupConfirmation: Bool"))
        XCTAssertTrue(widget.contains("var visualPhase: LiveIslandVisualPhase"))
        XCTAssertTrue(widget.contains("private var hasSkillIdentity: Bool"))
        XCTAssertTrue(widget.contains("private var isSkillExecutionPhase: Bool"))
        XCTAssertTrue(widget.contains("if isSkillExecutionPhase"))
        XCTAssertTrue(widget.contains("var moodText: String"))
        XCTAssertTrue(widget.contains("var skillStatusText: String"))
        XCTAssertTrue(widget.contains("var resultHeadline: String"))
        XCTAssertTrue(widget.contains("var resultPlainText: String"))
        XCTAssertFalse(widget.contains("var resultCompactLine: String"))
        XCTAssertTrue(widget.contains("var resultSummary: String"))
        XCTAssertFalse(widget.contains("var resultBulletLines: [String]"))
        XCTAssertFalse(widget.contains("var resultShowsSources: Bool"))
        XCTAssertFalse(widget.contains("var resultSourceMetadata: String?"))
        XCTAssertFalse(widget.contains("private var resultDetectedSourceCount: Int"))
        XCTAssertTrue(widget.contains("private var resultFallbackLine: String"))
        XCTAssertTrue(widget.contains("private func isResultSectionHeading(_ line: String) -> Bool"))
        XCTAssertTrue(widget.contains("private func isSourceMetadataLine(_ line: String) -> Bool"))
        XCTAssertTrue(widget.contains("private func strippingListMarker(from line: String) -> String"))
        XCTAssertTrue(widget.contains(#"^\[[^\]\n]{1,160}\]\(https?://[^)]+\)"#))
        XCTAssertTrue(widget.contains("glyph\n                .id(presentation.visualPhase)"))
        XCTAssertTrue(widget.contains("private var phaseTransition: AnyTransition"))
        XCTAssertTrue(widget.contains(".spring(response: 0.46, dampingFraction: 0.84, blendDuration: 0.08)"))
        XCTAssertTrue(widget.contains("HStack(alignment: .center, spacing: barSpacing)"))
        XCTAssertTrue(widget.contains("RoundedRectangle(cornerRadius: width / 2, style: .continuous)"))
        XCTAssertTrue(widget.contains("LinearGradient("))
        XCTAssertTrue(widget.contains("RadialGradient("))
        XCTAssertTrue(widget.contains("AngularGradient("))
        XCTAssertTrue(widget.contains("ForEach(0..<3, id: \\.self)"))
        XCTAssertTrue(widget.contains(".trim(from: segment.start, to: segment.end)"))
        XCTAssertTrue(widget.contains("private static let ringSegments: [(start: CGFloat, end: CGFloat)]"))
        XCTAssertTrue(widget.contains("(0.06, 0.20)"))
        XCTAssertTrue(widget.contains("(0.79, 0.91)"))
        XCTAssertTrue(widget.contains("let lineWidth = max(diameter * 0.108, 2.7)"))
        XCTAssertTrue(widget.contains(".frame(minWidth: 92, alignment: .trailing)"))
        XCTAssertTrue(widget.contains(".frame(minWidth: 72, alignment: .trailing)"))
        XCTAssertTrue(widget.contains("presentation.visualPhase == .skill || presentation.hasStartupConfirmation"))
        XCTAssertTrue(widget.contains("presentation.hasStartupConfirmation ? presentation.primaryLine : presentation.skillStatusText"))
        XCTAssertTrue(widget.contains("} else if presentation.hasStartupConfirmation {"))
        XCTAssertTrue(widget.contains("LiveIslandCompactTrailing(presentation: presentation)"))
        XCTAssertFalse(widget.contains("LiveIslandResultCompactPreview(presentation: presentation)"))
        XCTAssertTrue(widget.contains("Color.clear"))
        XCTAssertTrue(widget.contains("} else {\n                EmptyView()"))
        XCTAssertFalse(widget.contains(".frame(width: 18, height: 18)"))
        XCTAssertTrue(widget.contains("Text(presentation.moodText)"))
        XCTAssertFalse(widget.contains("Text(\"Thinking\")"))
        XCTAssertFalse(widget.contains("TimelineView("))
        XCTAssertFalse(widget.contains("sin("))
        XCTAssertFalse(widget.contains("cos("))
        XCTAssertFalse(widget.contains("frame(seconds:"))
        XCTAssertFalse(widget.contains("var showsContinuousMotion: Bool"))
        XCTAssertFalse(widget.contains("LivePhaseGlyph"))
        XCTAssertFalse(widget.contains("LivePhaseProgressBar"))
        XCTAssertFalse(widget.contains("LiveResultInfo"))
        XCTAssertFalse(widget.contains("ProgressView(timerInterval:"))
        XCTAssertFalse(widget.contains(".symbolEffect("))
        XCTAssertFalse(widget.contains("ProgressView()"))
        XCTAssertFalse(widget.contains("private let liveIslandFrameInterval"))
        // Result 是最大展开的信息面板; 动画只依靠状态切换, 不做自绘帧循环。
        XCTAssertFalse(widget.contains("LiveResultMark"))
        XCTAssertFalse(widget.contains("LiveAuroraCapsuleBackground"))
        XCTAssertFalse(widget.contains(".transition(.blurReplace)"))
        XCTAssertFalse(widget.contains("ForEach(0..<6, id: \\.self)"))
        XCTAssertFalse(widget.contains("let envelope = 0.62 + 0.38"))
        XCTAssertFalse(widget.contains(".rotationEffect(.degrees(t * 42.0))"))
        XCTAssertTrue(widget.contains("if phase == \"result\" { return .result }"))
        XCTAssertTrue(widget.contains("case \"skill\": return .executing"))
        XCTAssertFalse(widget.contains("if phase == \"skill\" || phase == \"result\" { return .result }"))
        XCTAssertTrue(widget.contains("case \"listening\", \"recording\": return .voice"))
        XCTAssertTrue(widget.contains("case \"understanding\", \"processing\": return .thinking"))
        XCTAssertTrue(widget.contains("case \"searching\": return .searching"))
        XCTAssertTrue(widget.contains("case \"executing\": return .executing"))
        XCTAssertTrue(widget.contains("case \"summarizing\", \"speaking\": return .responding"))
        XCTAssertTrue(widget.contains("case .starting, .voice, .thinking, .searching, .executing, .responding:\n            return .voice"))
        XCTAssertFalse(widget.contains("case .thinking, .searching, .executing, .responding:\n            return .skill"))
        XCTAssertTrue(widget.contains("case .starting, .voice, .thinking, .searching, .executing, .responding:\n            return \"聆听\""))
        XCTAssertFalse(widget.contains("case .thinking:\n            return \"理解\""))
        XCTAssertFalse(widget.contains("case .searching, .executing, .responding:\n            return \"执行\""))
        XCTAssertTrue(widget.contains("private static let skillStatusTexts: Set<String>"))
        XCTAssertTrue(widget.contains("\"正在查询\""))
        XCTAssertTrue(widget.contains("\"正在执行\""))
        XCTAssertTrue(widget.contains("\"正在处理\""))
        XCTAssertTrue(widget.contains("\"正在整理\""))
        XCTAssertTrue(widget.contains("case \"searching\":\n            return \"正在查询\""))
        XCTAssertTrue(widget.contains("case \"executing\":\n            return \"正在执行\""))
        XCTAssertTrue(widget.contains("case \"summarizing\":\n            return \"正在整理\""))
        XCTAssertTrue(widget.contains("return \"正在处理\""))
        XCTAssertTrue(widget.contains("state.success == false ? \"未完成\" : \"结果\""))
        XCTAssertFalse(widget.contains("\"已完成\""))
        XCTAssertFalse(widget.contains("return \"执行\""))
        XCTAssertTrue(widget.contains("case .voice, .thinking, .searching, .executing, .responding, .starting: return .amber"))
        XCTAssertTrue(widget.contains("case .result: return 24"))
        XCTAssertTrue(widget.contains("LiveSkillOrbitGlyph(presentation: presentation, diameter: diameter)"))
        XCTAssertTrue(widget.contains("LiveResultGlyph(presentation: presentation, diameter: diameter)"))
        XCTAssertFalse(widget.contains("var compactTitle: String"))
        XCTAssertFalse(widget.contains("var compactStageText: String"))
        XCTAssertFalse(widget.contains("var phaseStartedAt: Date?"))
        XCTAssertFalse(widget.contains("var statusText: String"))
        XCTAssertFalse(widget.contains("var iconName: String"))
        XCTAssertFalse(widget.contains("LiveCompactLeadingSurface(presentation: presentation)"))
        XCTAssertFalse(widget.contains("LiveCompactTrailingSurface(presentation: presentation)"))
        XCTAssertFalse(widget.contains("LiveCompactGlyph"))
        XCTAssertFalse(widget.contains("private struct LiveCompactHalo: View"))
        XCTAssertFalse(widget.contains("private struct LiveCompactStatusPulse"))
        XCTAssertFalse(widget.contains("private struct LiveProgressRing"))
        XCTAssertFalse(widget.contains("private struct LivePipelineTrack"))
        XCTAssertFalse(widget.contains("private func liveIsVoiceInputPhase"))
        XCTAssertFalse(widget.contains("private func liveIsThinkingPhase"))
        XCTAssertFalse(widget.contains("private func liveProgress(for state"))
    }

    func testLiveDynamicIslandExpandedModeUsesLargeLivePanel() throws {
        let widget = try source("PhoneClawLiveActivityWidget/PhoneClawLiveActivityWidget.swift")

        XCTAssertTrue(widget.contains("DynamicIslandExpandedRegion(.leading, priority: 2)"))
        XCTAssertTrue(widget.contains("if presentation.visualPhase == .result"))
        XCTAssertFalse(widget.contains("LiveIslandResultCompactTrailing(presentation: presentation)"))
        XCTAssertTrue(widget.contains("DynamicIslandExpandedRegion(.trailing, priority: 1)"))
        XCTAssertTrue(widget.contains("DynamicIslandExpandedRegion(.center, priority: 3)"))
        XCTAssertTrue(widget.contains("private struct LiveResultExpandedText: View"))
        XCTAssertFalse(widget.contains("private struct LiveIslandResultCompactTrailing: View"))
        XCTAssertFalse(widget.contains("private struct LiveIslandResultCompactPreview: View"))
        XCTAssertTrue(widget.contains("LiveResultExpandedText(presentation: presentation)"))
        XCTAssertTrue(widget.contains(".accessibilityLabel(Text(presentation.resultAccessibilityText))"))
        XCTAssertFalse(widget.contains("Text(presentation.resultCompactLine)"))
        XCTAssertFalse(widget.contains(".frame(width: 112, alignment: .trailing)"))
        XCTAssertFalse(widget.contains(".fixedSize(horizontal: true"))
        XCTAssertFalse(widget.contains("private struct LiveResultFooter: View"))
        XCTAssertTrue(widget.contains("private struct LiveMinimalActivityCard: View"))
        XCTAssertFalse(widget.contains("private enum LiveResultDensity"))
        XCTAssertFalse(widget.contains("ViewThatFits(in: .vertical)"))
        XCTAssertFalse(widget.contains("resultContent(density: .full)"))
        XCTAssertFalse(widget.contains("resultContent(density: .balanced)"))
        XCTAssertFalse(widget.contains("resultContent(density: .compact)"))
        XCTAssertTrue(widget.contains("Text(presentation.resultPlainText)"))
        XCTAssertTrue(widget.contains(".multilineTextAlignment(.leading)"))
        XCTAssertTrue(widget.contains(".frame(maxWidth: .infinity, alignment: .leading)"))
        XCTAssertFalse(widget.contains("Text(presentation.resultSummary)"))
        XCTAssertFalse(widget.contains("ForEach(presentation.resultBulletLines, id: \\.self)"))
        XCTAssertFalse(widget.contains("Image(systemName: \"sparkle\")"))
        XCTAssertFalse(widget.contains("density.showsBullets"))
        XCTAssertFalse(widget.contains("let showsSources = sourceMetadata != nil"))
        XCTAssertFalse(widget.contains("Text(sourceMetadata)"))
        XCTAssertFalse(widget.contains("Text(presentation.sourceMetadata)"))
        XCTAssertFalse(widget.contains("Text(\"来源\")"))
        XCTAssertTrue(widget.contains("Text(presentation.moodText)"))
        XCTAssertFalse(widget.contains("Text(\"Thinking\")"))
        XCTAssertTrue(widget.contains("if presentation.visualPhase == .result"))
        XCTAssertFalse(widget.contains(".offset(y: 2)"))
        XCTAssertFalse(widget.contains("RoundedRectangle(cornerRadius: 24, style: .continuous)"))
        XCTAssertFalse(widget.contains("ForEach(0..<6, id: \\.self)"))
        XCTAssertTrue(widget.contains("DynamicIslandExpandedRegion(.center"))
        XCTAssertFalse(widget.contains("LivePhaseProgressBar(presentation: presentation)"))
        XCTAssertFalse(widget.contains("presentation.showsContinuousMotion"))
        XCTAssertFalse(widget.contains("LiveIslandLeadingRail(presentation: presentation)"))
        XCTAssertFalse(widget.contains("LiveIslandCenterLabel(presentation: presentation)"))
        XCTAssertFalse(widget.contains("LiveIslandTrailingRail(presentation: presentation)"))
        XCTAssertFalse(widget.contains("LiveIslandBottomPanel(presentation: presentation)"))
        XCTAssertFalse(widget.contains("private struct LiveIslandSurroundingVisual: View"))
        XCTAssertFalse(widget.contains("private struct LiveExpandedVoiceWave: View"))
        XCTAssertFalse(widget.contains("private struct LiveExpandedThinkingGlyph: View"))
        XCTAssertFalse(widget.contains("private struct LiveExpandedSkillGlyph: View"))
        XCTAssertFalse(widget.contains("private struct LiveExpandedMilestones: View"))
        XCTAssertFalse(widget.contains("milestone(\"听\""))
        XCTAssertFalse(widget.contains("milestone(\"想\""))
        XCTAssertFalse(widget.contains("milestone(\"做\""))
        XCTAssertFalse(widget.contains("milestone(\"答\""))
        XCTAssertFalse(widget.contains("LiveDynamicIslandExpandedPanel"))
        XCTAssertFalse(widget.contains("LiveExpandedIslandVisualizer"))
    }

    func testLiveASRReusesMainAgentSkillChain() throws {
        let contentView = try source("UI/ContentView.swift")
        let liveModeUI = try source("Live/UI/LiveModeUI.swift")
        let liveModeEngine = try source("Live/Core/LiveModeEngine.swift")
        let liveWarmPool = try source("Live/Core/LiveWarmPool.swift")
        let liveActivityWidget = try source("PhoneClawLiveActivityWidget/PhoneClawLiveActivityWidget.swift")

        XCTAssertTrue(contentView.contains("agentEngine: engine"))
        XCTAssertTrue(liveModeUI.contains("let agentEngine: AgentEngine"))
        XCTAssertTrue(liveModeUI.contains("agentEngine: agentEngine"))
        XCTAssertTrue(liveModeUI.contains("liveEngine.setup(inference: inference, agentEngine: agentEngine)"))

        XCTAssertTrue(liveModeEngine.contains("private var agentEngine: AgentEngine?"))
        XCTAssertTrue(liveModeEngine.contains("processMainAgentTextTurn("))
        XCTAssertTrue(liveModeEngine.contains("await agentEngine.processInput(transcript)"))
        XCTAssertTrue(liveModeEngine.contains("liveInfoOutputFromMainAgentMessages"))
        XCTAssertTrue(liveModeEngine.contains("persistent live LLM conversation skipped"))
        XCTAssertTrue(liveModeEngine.contains("refusing LIVE-local Skill path"))
        XCTAssertTrue(liveModeEngine.contains("missing MAIN AgentEngine during ASR turn"))
        XCTAssertTrue(liveModeEngine.contains("didEnterLLMLiveMode"))
        XCTAssertTrue(liveModeEngine.contains("mainAgentTurnTimeout: TimeInterval = 180"))
        XCTAssertTrue(liveModeEngine.contains("liveTimedOutInfoOutput("))
        XCTAssertTrue(liveModeEngine.contains("main Agent turn still processing after"))
        XCTAssertTrue(liveModeEngine.contains("LiveAgentProgressSnapshot"))
        XCTAssertTrue(liveModeEngine.contains("publishMainAgentProgress("))
        XCTAssertTrue(liveModeEngine.contains("liveActivityListeningRefreshTask"))
        XCTAssertTrue(liveModeEngine.contains("scheduleLiveActivityListeningRefresh(afterResultGeneration: gen)"))
        XCTAssertTrue(liveModeEngine.contains("cancelLiveActivityListeningRefresh()"))
        XCTAssertTrue(liveModeEngine.contains("Task.sleep(for: .milliseconds(2500))"))
        XCTAssertTrue(liveModeEngine.contains("正在搜索相关信息，请稍等。"))
        XCTAssertTrue(liveModeEngine.contains("已检索到相关信息，正在整理答案。"))
        XCTAssertTrue(liveModeEngine.contains("已收到指令，请稍等。"))
        XCTAssertTrue(liveModeUI.contains("liveProgressHeadline"))
        XCTAssertTrue(liveActivityWidget.contains("if isSkillExecutionPhase {"))
        XCTAssertTrue(liveActivityWidget.contains("private static let skillStatusTexts: Set<String>"))
        XCTAssertTrue(liveActivityWidget.contains("state.success == false ? \"未完成\" : \"结果\""))
        XCTAssertFalse(liveActivityWidget.contains("\"已完成\""))
        XCTAssertTrue(liveActivityWidget.contains("case .starting, .voice, .thinking, .searching, .executing, .responding:\n            return \"聆听\""))
        XCTAssertFalse(liveActivityWidget.contains("case .thinking:\n            return \"理解\""))
        XCTAssertFalse(liveActivityWidget.contains("case .searching, .executing, .responding:\n            return \"执行\""))
        XCTAssertFalse(liveActivityWidget.contains("if isSkillExecutionPhase {\n            return \"执行\""))
        XCTAssertTrue(liveWarmPool.contains("agentEngine: AgentEngine"))
        XCTAssertTrue(liveWarmPool.contains("engine.setup(inference: inference, agentEngine: agentEngine)"))
        XCTAssertTrue(liveWarmPool.contains("func cancelPrewarm()"))
        XCTAssertFalse(liveWarmPool.contains("engine.setup(inference: inference)\n"))

        // LIVE must not rebuild tool arguments from ASR text. The ASR text is handed to
        // AgentEngine; Router/PromptBuilder/ToolChain remain the only Skill execution path.
        XCTAssertFalse(liveModeUI.contains("calendar-create-event\", \"arguments\""))
        XCTAssertFalse(liveModeUI.contains("reminders-create\", \"arguments\""))
        XCTAssertFalse(liveModeEngine.contains("calendar-create-event\", \"arguments\""))
        XCTAssertFalse(liveModeEngine.contains("reminders-create\", \"arguments\""))
        XCTAssertFalse(liveModeEngine.contains("LiveTurnProcessor("))
        XCTAssertFalse(liveModeEngine.contains("LiveSkillRouter"))
        XCTAssertFalse(liveModeEngine.contains("liveSkillRegistry"))
    }

    func testLiveDoesNotForceLiteRTLiveConversationForMainAgentMode() throws {
        let processor = try source("Live/Turn/LiveTurnProcessor.swift")
        let foundation = try source("Live/Turn/IOS27LiveFoundationTokenSource.swift")
        let liveModeEngine = try source("Live/Core/LiveModeEngine.swift")

        XCTAssertTrue(liveModeEngine.contains("guard agentEngine != nil"))
        XCTAssertFalse(liveModeEngine.contains("try await inference.enterLiveMode(systemPrompt: liveSystemPrompt)"))
        XCTAssertTrue(liveModeEngine.contains("didEnterLLMLiveMode = false"))
        XCTAssertTrue(liveModeEngine.contains("if didEnterLLMLiveMode"))

        // The older LIVE-local token source remains available as a non-default path, but
        // production LIVE from ContentView now passes AgentEngine and therefore uses MAIN.
        XCTAssertTrue(processor.contains("LiveTurnProcessor"))
        XCTAssertTrue(foundation.contains("#if canImport(FoundationModels)"))
        XCTAssertTrue(foundation.contains("if #available(iOS 27.0, macOS 26.0, *)"))

        // FM source must not introduce a second domain-specific Skill understanding layer.
        XCTAssertFalse(foundation.lowercased().contains("calendar"))
        XCTAssertFalse(foundation.lowercased().contains("reminder"))
        XCTAssertFalse(foundation.lowercased().contains("web-search"))
    }
}
